#- platform: mqtt
#  name: "Zanzito Status"
#  state_topic: "zanzito/mike/status"
#  payload_on: "1"
#  payload_off: "0"
#  device_class: connectivity
- platform: mqtt
  name: "Mike Charging Status"
  state_topic: "zanzito/mike/device_info"
  payload_on: "True"
  payload_off: "False"
#  device_class: power
  value_template: '{{ value_json.battery_charging }}'

- platform: mqtt
  name: "Tammy Charging Status"
  state_topic: "zanzito/tammy/device_info"
  payload_on: "True"
  payload_off: "False"
#  device_class: power
  value_template: '{{ value_json.battery_charging }}'
