homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 175
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Indiana/Indianapolis
  customize: !include customize.yaml

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/src/python-openzwave/openzwave/config/
  autoheal: true
  polling_interval: 45000

mqtt:
  broker: 127.0.0.1
  port: 1883

emulated_hue:
  host_ip: 192.168.9.42
  type: alexa
  expose_by_default: false
  off_maps_to_on_domains:
#  exposed_domains:
#    - script

automation: !include automations.yaml

#recorder:
#  purge_days: 3
#  exclude:
#    domains:
#      - automation
#      - updater
#      - group
#      - script
#    entities:
#      - sensor.average_load_15m
#      - sensor.since_last_boot
#      - sun.sun

group: !include groups.yaml

# Show links to resources in log and frontend introduction: Enables the
# frontend
frontend: 
http:
  server_port: 8123
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  # Uncomment this to add a password (recommended!)
  api_password: !secret password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled
# browsers
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
  exclude:
    entities:
      - sun.sun
#      - sensor.dark_sky_minutely_summary
#      - sensor.dark_sky_hourly_summary
#      - sensor.dark_sky_daily_summary

# Track the sun
sun:
# Weather Prediction
sensor: !include sensors.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include camera.yaml
# Text to speech
tts:
  platform: google

script: !include scripts.yaml

switch: !include switches.yaml

notify: !include notify.yaml

device_tracker: !include device_trackers.yaml

zone: !include zones.yaml

input_select: !include input_selects.yaml

input_number: !include input_numbers.yaml

shell_command:
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01 

telegram_bot:
- platform: webhooks
#- platform: polling
  parse_mode: html
  api_key: !secret telegram_api
  allowed_chat_ids:
    - 315019903

