#- platform: unifi
#  host: 192.168.8.71
#  port: 8443
#  username: admin
#  password: 83ade57
#  site_id: montgomery
#  track_new_devices: no
#  interval_seconds: 12
#  consider_home: 180
#  verify_ssl: false
#- platform: owntracks
#  max_gps_accuracy: 200
- platform: mqtt_json
  devices:
    mike: zanzito/mike/location
    tammy: zanzito/tammy/location

